name: "Test Trivy Image Scan"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      image_to_scan:
        description: 'Docker image to scan'
        required: true
        default: 'Dockerfile'

jobs:
  test-trivy:
    uses: ./.github/workflows/trivy_test.yml
    with:
      dockerfile_name: Dockerfile
    secrets:
      github_token_value: ${{ secrets.GITHUB_TOKEN }}
