name: Run Trivy Scan Manually

on:
  workflow_dispatch:
    inputs:
      image_to_scan:
        description: 'Docker image to scan'
        required: true
        default: 'nginx:latest'

jobs:
  test-trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        id: trivy-scan
        with:
          image-ref: ${{ github.event.inputs.image_to_scan }}
