name: trivy_scan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/juice-shop:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        run: |
          trivy image \
            --db-repository public.ecr.aws/aquasecurity/trivy-db \
            --java-db-repository public.ecr.aws/aquasecurity/trivy-java-db \
            --format table \
            --ignore-unfixed \
            --vuln-type os,library \
            --severity CRITICAL,HIGH \
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/juice-shop:${{ github.sha }}
