name: Trivy Test Scan

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  test-trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy Test Scan on nginx:latest
        uses: aquasecurity/trivy-action@master
        id: trivy-scan
        with:
          image-ref: "nginx:latest"  # Specify any publicly available Docker image
        continue-on-error: false  # Ensure the job fails if vulnerabilities are found
